### ISSUE TITLE
version 4.1.x tracking issue

### ISSUE THREAD

**Issue by hoank101** [White-Whale-Defi-Platform/migaloo-chain#297]
Across:

* Upgrade cosmos-sdk from v0.46.15 -> v0.47.7
* Upgrade ibc v6 -> v7, use original IBC
* Upgrade wasmd v0.30.0 -> v0.45.0, use original wasmd
* Upgrade tokenfactory use terra version
* Add feeburn module

## Version 4.1.x
- [x] Upgrade cosmos-sdk from v0.46.15 -> v0.47.7
- [x] Use the latest ibc-go/v7
- [x] Upgrade wasmd v0.30.0 -> v0.45.0, use original wasmd
     - [x] #291 
     - [x] #293  
     - [x] #316 
- [x] Upgrade tokenfactory use terra version
  - [x]  #292 
  - [x]  #294
- [x] Add feeburn module 
  - [x] #299  
  - [x] Gov proposal update tx_fee_burn_percent
- [x] Add more tests for chain upgrade
   - [x] #298    
   - [x] #302
- [x] #322 Moves the vested and reward token from the ContinuousVestingAccount of Notional Team to new multisig account.
