### ISSUE TITLE
Mainnet Prelaunch Checklist

### ISSUE THREAD

**Issue by faddat** [White-Whale-Defi-Platform/migaloo-chain#77]
**In this repository**
- [x] Migaloo should pass all tests
  - [x] https://github.com/White-Whale-Defi-Platform/migaloo-chain/pull/78 
- [x] Test for packet forward middleware
- [x] cmd folder restructured to the exact style of sdk v0.46.x simapp
- [x] double check that key PR's got into the release/v1.0.x branch, which is now the default branch, to prevent confusion
- [x] Security checks should be resolved (see the security tab in github), and note that not every flagged item is a security risk
- [x] modify pregenesis to have state for packet forward middleware
  - [x] collect new genesis transactions if that ends up being necessary
- [x] resolve issue with cli:
  * #89 
- [x] check to ensure that we're not setting bech32 addresses with a cosmos address

**Upstream Work outside this repository**

- [x] wasmd release/v0.30.0-sdk-v0.46.x should be linted and pass all tests
  - [x] make token factory a part of wasmd so that it can be tested with wasmd 
  - [x] tests: https://github.com/notional-labs/wasmd/pull/80
  - [x] lint 
  - [x] refactor token factory tests to use the sdk v0.46.x approach: 
    - [x] https://github.com/notional-labs/wasmd/pull/81

**Comment by faddat** [comment]
Things validators can do whilst waiting for each tick box above to be ticked:

* star the repo
* help to tick tickboxes
* check through the code, and create an issue with the results of your findings

There are rumors, that delegators love to see this kinda stuff.

New planned launch date is Monday, but will give go/no go on that by midnight on Sunday in Hanoi.  

Things look fine -- this is mainly cleanup work, to ensure that nothing explodes along the way.  Huge ups to @pysel for catching a bug during review!

**Comment by faddat** [comment]
Looks to me like we are a go for Monday.  This isn't final, and is the sole decision of the white whale team, but #82 gets us where we need to go to feel good and stable about launch.

**Comment by faddat** [comment]
Hey, the issue with bech32 prefixes is indeed real.  I assume that we are not calling the correct function to populate them, and will resolve that tomorrow.

```
migalood keys add test
Enter keyring passphrase:

- address: cosmos13d7dft23xmls0tdav3ydap5ze0k042v3ywgtvk
  name: test
  pubkey: '{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AupfjuaN4cTBlO7Jab8InOiYayHG8uVgLOMutw1HCXNR"}'
  type: local


```

**Comment by faddat** [comment]
We're good. and now collecting genesis transactions.
